### ISSUE TITLE
mph2kph.pnach do not seems to work

### ISSUE THREAD

**Issue by Naworm** [Nahelam/PCSX2-Burnout-3-Takedown-Mods#1]
https://github.com/Nahelam/PCSX2-Burnout-3-Takedown-Mods/blob/main/Various/SLUS-21050/BEBF8793_mph2kph.pnach

**Comment by Nahelam** [comment]
It works fine on my side, note that it affects the speedometer only. Make sure to choose the correct region and set the correct CRC in the file name if you're using a modified ISO.

**Comment by Naworm** [comment]
All my others patches works except this one:
CRC is OK see : 
![image](https://github.com/Nahelam/PCSX2-Burnout-3-Takedown-Mods/assets/48997616/a4ca72fb-026b-45e2-bfea-265863379119)

My only exception is that I am running on a EUR BIOS (SCPH-77004_BIOS_V15_EUR_220.ROM0)

**Comment by Nahelam** [comment]
I can't reproduce it, I ran the game on the same BIOS and it worked fine, I also tried toggling widescreen patches, works fine too. Something is going wrong with your settings, you have to troubleshoot it, try running the game with all other cheats disabled etc.

Are you loading a save state? PCSX2 won't load new cheats when you load from a save state iirc.

**Comment by Naworm** [comment]
Yes sorry I was loading state every time :/
So it fixed now thank you !

Then I had issues with this patch breaking widescreen
```
; // 480p - enables progre
ssive scan (no need to set it when launching the game)
; patch=1,EE,20675F34,extended,00000000
```

Haven't you "No Interlacing Patches" for SLUS-21050 ?
Even if changing on boot is ok since I using savestate...

**Comment by Nahelam** [comment]
Glad you got it working!

Regarding no interlacing patches, your message made me want to make one for **SLUS-21050** which I did and I just pushed it:

https://github.com/Nahelam/PCSX2-Burnout-3-Takedown-Mods/blob/main/No%20Interlacing%20Patches/SLUS-21050/BEBF8793_no_interlacing.pnach

Using this patch will make the game always ask you if you want to enable 480p during boot.

**Comment by Naworm** [comment]
You new patch working for me too.
Just curious, you didn't manage to fix the old one ? Or the widescreen patch is blocking it for good ?

**Comment by Nahelam** [comment]
I don't know how the old one was made/behaves, but apparently it isn't working in all cases thus I made another one that I exactly know what it does. Always bringing up the original 480p prompt when game starts is the cleanest way of enabling progressive scan imo.
